name: Consume GitHub Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get Token GH App  # Need it in order to write to comment section
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3  
        with:
          application_id: ${{ secrets.APPLICATION_ID }}     # Need create a secret in actions
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Extend Git credentials  # For terraform modules to use. Can download modules from git
        uses: de-vri-es/setup-git-credentials@v2.0.10
        with:
          credentials: https://x-access-token:${{ steps.get_workflow_token.outputs.token }}@github.com

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>x-access-token</username>
                <password>${{ steps.get_workflow_token.outputs.token }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Build and run
        run: |
          mvn compile
          mvn exec:java -Dexec.mainClass="com.example.App"
